language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lihq1403"
  - git config user.email "lihaiqing1994@163.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://${CD_USER}:${CD_TOKEN}@${CD_REF}" master:master

branches:
  only:
    - hexo
